###############################################################################
# Copyright (c) 2024 Robert Bosch Manufacturing Solutions GmbH and others
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################################

openapi: 3.0.3
info:
  title: HTTP/REST | Access Rule management API
  description: "Access Rule management endpoints"
  contact:
    name: TBD
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: V1.0
security:
  - bearerAuth: []
servers:
  - url: "{protocol}://{host_name}:{port}{context_root}/api/{version_prefix}/"
    variables:
      protocol:
        description: Allows access through http and https (recommended)
        default: https
        enum:
          - http
          - https
      host_name:
        description: Hostname of server hosting the api
        default: localhost
      port:
        description: "80 is default for http, 443 for https"
        default: "443"
        enum:
          - "80"
          - "443"
          - "4243"
      version_prefix:
        default: v3.0
        enum:
          - v3.0
      context_root:
        description: Context root for the API
        default: ""
paths:
  /access-controls/rules:
    get:
      tags:
        - Access Rule
      summary: Returns a list of Access Rule
      operationId: GetAllAccessRules
      responses:
        "200":
          description: The Access Rules
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: './access-control-openapi_schemas.yaml#/schemas/ReadUpdateAccessRule'
                required:
                  - items
                additionalProperties: false
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
    post:
      tags:
        - Access Rule
      summary: Creates a new Access Rule
      operationId: CreateNewAccessRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: './access-control-openapi_schemas.yaml#/schemas/CreateAccessRule'
      responses:
        "201":
          description: Successfully created the Access Rule
          content:
            application/json:
              schema:
                $ref: './access-control-openapi_schemas.yaml#/schemas/ReadUpdateAccessRule'
        "400":
          description: Bad request (e.g. invalid input)
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
  /access-controls/rules/{ruleId}:
    get:
      tags:
        - Access Rule
      summary: Returns a single Access Rule by Rule Id
      operationId: GetAccessRuleByRuleId
      parameters:
        - $ref: './access-control-openapi_schemas.yaml#/parameters/RuleId'
      responses:
        "200":
          description: The Access Rule
          content:
            application/json:
              schema:
                $ref: './access-control-openapi_schemas.yaml#/schemas/ReadUpdateAccessRule'
        "400":
          description: Bad request (e.g. invalid input)
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: The Access Rule is not found
        "500":
          description: Internal server error
    put:
      tags:
        - Access Rule
      summary: Updates an Access Rule by Rule Id
      operationId: UpdateAccessRuleByRuleId
      parameters:
        - $ref: './access-control-openapi_schemas.yaml#/parameters/RuleId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './access-control-openapi_schemas.yaml#/schemas/ReadUpdateAccessRule'
      responses:
        "200":
          description: Successfully updated the Access Rule
          content:
            application/json:
              schema:
                $ref: './access-control-openapi_schemas.yaml#/schemas/ReadUpdateAccessRule'
        "400":
          description: Bad request (e.g. invalid input)
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: The Access Rule is not found
        "500":
          description: Internal server error

    delete:
      tags:
        - Access Rule
      summary: Deletes an Access Rule by Rule Id
      operationId: DeleteAccessRuleByRuleId
      parameters:
        - $ref: './access-control-openapi_schemas.yaml#/parameters/RuleId'
      responses:
        "204":
          description: Successfully deleted the Access Rule
        "400":
          description: Bad request (e.g. invalid input)
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: The Access Rule is not found
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
