################################################################################
# Copyright (c) 2021 T-Systems International GmbH and others
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

server:
  port: 4243
  ssl:
    key-store-password: __KEYSTOREPASSWORD__
    key-store: classpath:conf/__KEYSTOREFILENAME__.p12
    key-store-type: PKCS12
    key-alias: 1
    enabled: false
  forward-headers-strategy: framework

http:
  timeout:
    write: 10000
    connect: 10000
    call: 10000
    read: 10000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: semantics-services
  banner:
    location: "classpath:banner.txt"
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB
  jackson:
    default-property-inclusion: non_null
  # override this in environment variables
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: "http://localhost:9090/auth/realms/CX-Central"

registry:
  # This wildcard prefix is used to make specificAssetIds public vor everyone.
  # The default-value "PUBLIC_READABLE" is used by all catenaX participants.
  external-subject-id-wildcard-prefix: PUBLIC_READABLE
  external-subject-id-wildcard-allowed-types:
  idm:
    public-client-id: catenax-portal
  use-granular-access-control: false

springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: false
  swagger-ui:
    path: /
    urls:
     - name: AAS Registry API
       url: /aas-registry-openapi.yaml
    oauth:
      use-pkce-with-authorization-code-grant: true
      # the scopes and client id will be prefilled in the swagger ui
      scopes: openid profile
      client-id: ${registry.idm.public-client-id}

title: '@project.name@'
project_desc: '@project.description@'
contact_email: '@email@'
licence: '@licence_name@'
contact_url: '@project.url@'
licence_url: '@licence_url@'
organization_name: '@project.organization.name@'
version: '@project.version@'
    
management:
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
