################################################################################
# Copyright (c) 2021 Robert Bosch Manufacturing Solutions GmbH and others
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

---
name: "Create new version tag"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      release_docker_image:
        description: 'Should we release the Docker image?'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      release_edc:
        description: 'Should we release the EDC extension?'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Merge changes from main
        run: |
          git merge origin/main
      - name: Run tests and adjust version
        run: |
          mvn clean package
          mvn versions:set -DnewVersion=${{ inputs.version }}
          mvn versions:commit
      - name: Create tag, commit and push
        run: |
          git add .
          git commit -m "Create version v${{ inputs.version }}"
          git tag v${{ inputs.version }}
          git push origin release
          git push origin v${{ inputs.version }}
  call-image-release:
    if: ${{ inputs.release_docker_image == 'yes' }}
    uses: ./.github/workflows/publish-image-registry.yml
    needs: build
    secrets: inherit
    with:
      tag: v${{ inputs.version }}
  call-edc-maven-central-publish:
    if: ${{ inputs.release_edc == 'yes' }}
    uses: ./.github/workflows/publish-edc-ext-to-maven-central.yml
    needs: build
    secrets: inherit
    with:
      tag: v${{ inputs.version }}